const DIRECTION_RIGHT = "right";
const DIRECTION_LEFT = "left";
const ACTION_SHOOT = "shoot";
const KEYBOARD_LEFT = "ArrowLeft";
const KEYBOARD_RIGHT = "ArrowRight";
const KEYBOARD_SPACE = "Space";
const DEFAULT_SCORE_INCREMENT = 10;
const DEFAULT_SCORE = 0;
const DEFAULT_SHIP_X = 220;
const DEFAULT_SHIP_Y = 500;
const DEFAULT_SHIP_WIDTH = 60;
const DEFAULT_SHIP_HEIGHT = 32;
const DEFAULT_SHIP_SPEED = 17;
const DEFAULT_INVADER_X = 20;
const DEFAULT_INVADER_Y = 50;
const DEFAULT_INVADER_WIDTH = 48;
const DEFAULT_INVADER_HEIGHT = 32;
const DEFAULT_BOARD_INVADER_TRAVEL = 50;
const DEFAULT_BOARD_INVADER_VELOCITY = 250;
const DEFAULT_TIME_INVADER_DROP = 5000;
const DEFAULT_SWARM_X = 20;
const DEFAULT_SWARM_Y = 50;
const DEFAULT_SWARM_ROWS = 4;
const DEFAULT_SWARM_SPACE = 10;
const DEFAULT_BOARD_SWARM_VELOCITY = 3000;
const DEFAULT_BOARD_SWARM_TRAVEL = 20;
const DEFAULT_BULLET_WIDTH = 6;
const DEFAULT_BULLET_HEIGHT = 17;
const DEFAULT_BULLET_SPACE = 30;
const DEFAULT_BOARD_BULLET_TRAVEL = 30;
const DEFAULT_BOARD_BULLET_VELOCITY = 200;



